#!/bin/bash
# Do not turn on -x here. it will screw things up!

l=`pwd`
#echo $l
lb=`basename $l`
ld=`dirname $l`
#echo " lb: $lb"
#echo " ld: $ld"
cdtarg=.
sloc=$l/scripts
if [ x$lb = "xscripts" ]
then
  ldb=`basename $ld`
  cd ..
  if [ $? -ne 0 ]
  then
     echo "cd .. failed, giving up."
     exit 1
  fi
  sloc=$l
fi
l=`pwd`
echo "Now in $l"
if [ ! -d scripts ]
then
   echo "Not in the right directory, scripts directory missing"
   echo "In " `pwd`
   exit 1
fi
if [ ! -d src ]
then
   echo "Not in the right directory, src directory missing"
   echo "In " `pwd`
   exit 1
fi
if [ ! -f src/readelfobj_version.h ]
then
   echo "Not in the right directory, readelfobject source file missing"
   echo "In " `pwd`
   exit 1
fi
echo "Now at $l"
echo "sloc $sloc"

x=`date --rfc-3339=seconds |tr '\n' ' '`
cat > $sloc/UPD.awk <<\EOF
BEGIN {
if (ARGC <=  2)  {
    print "Bogus use of awk file, requires arg"
    exit 1   
} else  {
    v=ARGV[1]
    ARGV[1]=""
}
}
$0 ~  /#define READELFOBJ_VERSION_DATE_STR/ { print $1, $2, "\"",v,"\"" }
$0 !~ /^#define READELFOBJ_VERSION_DATE_STR/ { print $0 }
EOF
awk -f $sloc/UPD.awk  "$x"  $l/src/readelfobj_version.h >t
mv t $l/src/readelfobj_version.h

